---
- name: Get current working dir
  command: /bin/pwd
  register: cwd
  check_mode: no
  changed_when: False
- name: Shortening name
  set_fact:
    host_basename: "{{ inventory_hostname | regex_replace('\\.(example.com|example.net)$', '') }}"
- name: Setting paths
  set_fact:
    build_dir: "{{ cwd.stdout }}/../temp/build/{{ host_basename }}.d"
    config_dir: "{{ cwd.stdout }}/../configs/{{ host_basename }}.d/"
    temp_dir: "{{ cwd.stdout }}/../temp/"
    peers_dir: "{{ cwd.stdout }}/../peers/"
- name: Defining files
  set_fact:
    config_file: "{{ config_dir }}/bird.conf"
    cache_file: "{{ cwd.stdout }}/../temp/cache.yml"
    addon_file: "{{ cwd.stdout }}/../peers/addon.yml"
